### PR TITLE
Add Rules to ordering

### PR DESCRIPTION
**Pull request by jameslevine**
Issue #, if available:
No Issue

Description of changes:
We currently have Rules in our CloudFormation template. It looks like, since this isn't included in the ordering, it automatically gets pushed at the bottom of the file. 

It would be nice to see Rules being consistently placed in the same position in the template.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ctd** [comment]
Perhaps `Rules` should be after `Parameters`, per the [anatomy documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html#template-anatomy-outline.yaml)?

**Comment by jameslevine** [comment]
> Perhaps `Rules` should be after `Parameters`, per the [anatomy documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html#template-anatomy-outline.yaml)?

Thanks, this is a good point, I have updated to follow this.

**Comment by jameslevine** [comment]
I have now updated the tests to include Rules too.

**Comment by ConnorKirk** [comment]
I'm not strictly the maintainer for this project, so I'll defer review to someone more official 😄 

I'd consider this a minor breaking change. Before this change `rain` would format your template with `Rules` at the end of the template. 

After this change the rules section will be below the `Parameters` section. Might be a minor annoyance if you version control your templates.

**Comment by stilvoid** [comment]
lgtm pending commit history tidy up :)

**Review by stilvoid — APPROVED** [review]
lgtm :+1:

**Pull request merged**
