### PR TITLE
Package Command Should Preserve Map Key Order

### PR DESCRIPTION
**Pull request by null93**
*Issue #, if available:*

Fixes aws-cloudformation/rain#362

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ericzbeard** [comment]
Looks like this change broke anchors. Maybe we need to look for another way to support anchors, since the Decode/Encode was an expedient solution that had unwanted side effect (like losing line numbers).

**Comment by null93** [comment]
Didn't see that coming lol. I can take another look later to see what I can come up with.

**Comment by null93** [comment]
@ericzbeard 

I think I got it to work. I had to modify the test file as well since order needed to be reflected in the expected result (and style).

I added a visitor package under cft and used it to manually resolve the alias nodes. I still had to Marshal and Unmarshal the result so line numbers get updated on the anchored nodes.

Let me know if anything needs changing.

**Review by ericzbeard — APPROVED** [review]

**Comment by null93** [comment]
@ericzbeard Thanks for merging this PR in! Does this project release on a certain schedule? I am just wondering when the next release will be with this fix implemented.

**Comment by ericzbeard** [comment]
I'll get one out today or tomorrow. No schedule, just whenever there are features and fixes ready to go out.

**Comment by ericzbeard** [comment]
https://github.com/aws-cloudformation/rain/releases/tag/v1.8.6

**Pull request merged**
